name: Application Build and Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
            aws-region: "us-east-1"
      
      - name: Build with Docker
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ github.sha }} . 

      - name: Push the image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  ${{ secrets.IMAGE_NAME }}
          docker image push ${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition toomio-backend --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: toomio-backend
          image: ${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-definition.outputs.task-definition }}
          service: toomio-backend
          cluster: toomio-backend
          wait-for-service-stability: true